spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver # 이렇게 설정하면 히카리 풀 을 써서 세팅을 해줌

  jpa:
    hibernate:
      ddl-auto: update # create - 자동 새성
    properties:
      hibernate:
        session_factory :
          statement_inspector : jpabook.jpashop_v2.config.HibernateInterceptor
        default_batch_fetch_size : 100
#        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: true # default option
logging:
  level:
    org.hibernate.SQL: debug # 이 녀석은 로거를 통해 찍는 것이고, 따라서 show_sql 은 운영에선 사용하면 안됨.
